// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using peroline.FaultTolerance;

namespace peroline.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20211011035256_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("peroline.FaultTolerance.ErrorMemo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataForRetry")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasBeenRetried")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumOfRetry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecoveryFor")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetriedByBotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ErrorMemo");
                });
#pragma warning restore 612, 618
        }
    }
}
